// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxcpnitxkhmfpvbxgpqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Y3BuaXR4a2htZnB2YnhncHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTYxMzEsImV4cCI6MjA2ODkzMjEzMX0.QEml3Q79HogSid63QsO4bJkoVhuQwlQWLfyTUPG74w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});